report-finder-package-md-source/objects/Report_Finder_Item__c.object
<CustomObject>
    <description>These records hold details about reports, including filters, tags, types, and thumbnails.</description>
    <label>Report Finder Item</label>
    <nameField>
        <displayFormat>RFI-{0}</displayFormat>
        <label>Report Finder Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Finder Items</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Access_URL__c</fullName>
        <label>Access URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Item_Name__c</fullName>
        <label>Item Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Long_Description__c</fullName>
        <label>Long Description</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Publish_Status__c</fullName>
        <label>Publish Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Not Published</fullName>
                </value>
                <value>
                    <fullName>Beta</fullName>
                    <isActive>false</isActive>
                    <label>Beta</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Thumbnail_URL__c</fullName>
        <label>Thumbnail URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce Dashboard</fullName>
                </value>
                <value>
                    <fullName>Salesforce Report</fullName>
                </value>
                <value>
                    <fullName>Salesforce View</fullName>
                </value>
                <value>
                    <fullName>Tableau Dashboard</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/ReportThumbnailController.cls
/**
* @author Ben Repak u0884669
* @date 2022-September
*
* @description Controller used in the Report Finder App to update Thumbnail photos 
*/
public with sharing class ReportThumbnailController {

    private static String thumbnailUrl;
    


    @AuraEnabled
    public static ReportFinderController.ReportInfo getReport(String recordId){
        system.debug('recordId --> ' + recordId);

        Report_Finder_Item__c rfi = new Report_Finder_Item__c();
        string queryString =    'SELECT Id, Item_Name__c,Thumbnail_URL__c, Name, Long_Description__c,Short_Description__c, Type__c, Publish_Status__c, Access_URL__c ' + 
        ' FROM Report_Finder_Item__c ' +
        ' WHERE Id = :recordId';
        rfi = database.query(queryString);
        ReportFinderController.ReportInfo report = new ReportFinderController.ReportInfo(rfi);
        return report;
        

    }

  

    @AuraEnabled
    public static String updateThumbnail(String contentVersionId, String contentDocumentId, String recordId) {
      if (contentVersionId == null || recordId == null || contentDocumentId == null) { return null; }
       
      try {
       
        Report_Finder_Item__c rfi = new Report_Finder_Item__c();
        rfi.Id = recordId;
        rfi.Thumbnail_Url__c = System.URL.getSalesforceBaseUrl().toExternalForm()+'/sfc/servlet.shepherd/version/renditionDownload?rendition=THUMB720BY480&versionId=' 
        +  contentVersionId
        + '&operationContext=CHATTER&contentId='
        + contentDocumentId;
        update rfi;
        system.debug('rfi --> ' + rfi);
        return rfi.Thumbnail_Url__c;
      } catch(DMLException e) {
        system.debug('error');
        System.debug(e.getMessage());
        return null;
      }
    }

}