report-finder-package-md-source/objects/Report_Finder_Category__c.object
<CustomObject>
    <description>Tags that can be applied to organize and filter Report Finder Items</description>
    <label>Report Finder Category</label>
    <nameField>
        <displayFormat>RFC-{0}</displayFormat>
        <label>Report Finder Category #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Finder Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Category_Name__c</fullName>
        <label>Category Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

report-finder-package-md-source/objects/Report_Finder_Category_Filter__c.object
<CustomObject>
    <description>Junction object linking Report Finder Item and Report Finder Category</description>
    <label>Report Finder Category Filter</label>
    <nameField>
        <displayFormat>RFCF-{0}</displayFormat>
        <label>Report Finder Category Filter #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Finder Category Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Report_Finder_Category__c</fullName>
        <label>Report Finder Category</label>
        <referenceTo>Report_Finder_Category__c</referenceTo>
        <relationshipName>Report_Finder_Category_Filters</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Report_Finder_Item__c</fullName>
        <label>Report Finder Item</label>
        <referenceTo>Report_Finder_Item__c</referenceTo>
        <relationshipLabel>Report Finder Category Filters</relationshipLabel>
        <relationshipName>Report_Finder_Category_Filters</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

report-finder-package-md-source/objects/Report_Finder_Item__c.object
<CustomObject>
    <description>These records hold details about reports, including filters, tags, types, and thumbnails.</description>
    <label>Report Finder Item</label>
    <nameField>
        <displayFormat>RFI-{0}</displayFormat>
        <label>Report Finder Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Finder Items</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Access_URL__c</fullName>
        <label>Access URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Item_Name__c</fullName>
        <label>Item Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Long_Description__c</fullName>
        <label>Long Description</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Publish_Status__c</fullName>
        <label>Publish Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Not Published</fullName>
                </value>
                <value>
                    <fullName>Beta</fullName>
                    <isActive>false</isActive>
                    <label>Beta</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Thumbnail_URL__c</fullName>
        <label>Thumbnail URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce Dashboard</fullName>
                </value>
                <value>
                    <fullName>Salesforce Report</fullName>
                </value>
                <value>
                    <fullName>Salesforce View</fullName>
                </value>
                <value>
                    <fullName>Tableau Dashboard</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

report-finder-package-md-source/objects/Report_Finder_Job_Function__c.object
<CustomObject>
    <description>Tags that can be applied to organize and filter Report Finder Items. Relevant to job functions within the organization.</description>
    <label>Report Finder Job Function</label>
    <nameField>
        <displayFormat>RFJF-{0}</displayFormat>
        <label>Job Function #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Finder Job Functions</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Job_Function_Name__c</fullName>
        <label>Job Function Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

report-finder-package-md-source/objects/Report_Finder_Job_Function_Filter__c.object
<CustomObject>
    <description>Junction object between Report Finder Item and Report Finder Job Function</description>
    <label>Report Finder Job Function Filter</label>
    <nameField>
        <displayFormat>RFJBF-{0}</displayFormat>
        <label>Job Function Filter #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Finder Job Function Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Job_Function__c</fullName>
        <label>Job Function</label>
        <referenceTo>Report_Finder_Job_Function__c</referenceTo>
        <relationshipLabel>Report Finder Job Function Filters</relationshipLabel>
        <relationshipName>Report_Finder_Job_Function_Filter</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Report_Finder_Item__c</fullName>
        <label>Report Finder Item</label>
        <referenceTo>Report_Finder_Item__c</referenceTo>
        <relationshipLabel>Report Finder Job Function Filters</relationshipLabel>
        <relationshipName>Report_Finder_Job_Function_Filter</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/classes/ReportFinderFilterController_TEST.cls
/**
* @author Ben Repak u0884669
* @date 2022-September
*
* @description Test class for ReportFinderFilterController
*/
@isTest
public with sharing class ReportFinderFilterController_TEST {

    @TestSetup
    private static void makeData(){
        // create a test Report_Finder_Item__c record for assignments later
        Report_Finder_Item__c rfi = new Report_Finder_Item__c();
        rfi.Item_Name__c = 'Test Report Finder Item';
        rfi.Short_Description__c = 'Short Description';
        rfi.Long_Description__c = 'Long Description';
        rfi.Publish_Status__c = 'Published';
        rfi.Type__c = 'Tableau Dashboard';
        rfi.Access_URL__c = 'https://utah.edu';
        rfi.Thumbnail_URL__c = '/bogus_url/';
        insert rfi;

        // create Report_Finder_Job_Function__c data 
        List<Report_Finder_Job_Function__c> jobs = new List<Report_Finder_Job_Function__c>();
        Report_Finder_Job_Function__c activeJob = new Report_Finder_Job_Function__c();
        activeJob.Is_Active__c = true;
        activeJob.Job_Function_Name__c = 'Active Job';
        jobs.add(activeJob);
        Report_Finder_Job_Function__c inactiveJob = new Report_Finder_Job_Function__c();
        inactiveJob.Is_Active__c = false;
        inactiveJob.Job_Function_Name__c = 'Inactive Job';
        jobs.add(inactiveJob);

        insert jobs;

        // create Report_Finder_Category__c data 
        List<Report_Finder_Category__c> categories = new List<Report_Finder_Category__c>();
        Report_Finder_Category__c activeCategory = new Report_Finder_Category__c();
        activeCategory.Is_Active__c = true;
        activeCategory.Category_Name__c = 'Active Category';
        categories.add(activeCategory);
        Report_Finder_Category__c inactiveCategory = new Report_Finder_Category__c();
        inactiveCategory.Is_Active__c = false;
        inactiveCategory.Category_Name__c = 'Inactive Category';
        categories.add(inactiveCategory);

        insert categories;

    }

    /*******************************************************************************************************
    * @description Tests retrieving active and assigned records
    */
    @isTest
    private static void testRetrieveJobsWithFilters(){

        // get report from setup method
        Report_Finder_Item__c rfi = [SELECT Id FROM Report_Finder_Item__c WHERE Item_Name__c = 'Test Report Finder Item'][0];

        // get filter from setup method
        Report_Finder_Job_Function__c job = [SELECT Id FROM Report_Finder_Job_Function__c WHERE  Job_Function_Name__c = 'Active Job'][0];

        // create a filter on a report so the value is loaded in the controller
        Report_Finder_Job_Function_Filter__c jobFilter = new Report_Finder_Job_Function_Filter__c();
        jobFilter.Job_Function__c = job.Id;
        jobFilter.Report_Finder_Item__c = rfi.Id;
        insert jobFilter;

        List<String> results;
        Integer countResults;

        Test.startTest();
        results = ReportFinderFilterController.getJobFunctions();
        Test.stopTest();

        countResults = results.size();

        System.assertEquals(1, countResults, 'Expect 1 active record to be returned');
    }


    /*******************************************************************************************************
    * @description Tests retrieving active and assigned records
    */
    @isTest
    private static void testRetrieveCategoriesWithFilters(){

        // get report from setup method
        Report_Finder_Item__c rfi = [SELECT Id FROM Report_Finder_Item__c WHERE Item_Name__c = 'Test Report Finder Item'][0];

        // get filter from setup method
        Report_Finder_Category__c category = [SELECT Id FROM Report_Finder_Category__c WHERE  Category_Name__c = 'Active Category'][0];

        // create a filter on a report so the value is loaded in the controller
        Report_Finder_Category_Filter__c categoryFilter = new Report_Finder_Category_Filter__c();
        categoryFilter.Report_Finder_Category__c = category.Id;
        categoryFilter.Report_Finder_Item__c = rfi.Id;
        insert categoryFilter;

        List<String> results;
        Integer countResults;

        Test.startTest();
        results = ReportFinderFilterController.getCategories();
        Test.stopTest();

        countResults = results.size();

        System.assertEquals(1, countResults, 'Expect 1 active record to be returned');
    }


    /*******************************************************************************************************
    * @description Tests retrieving active records that are not assigned to any report
    */
    @isTest
    private static void testRetrieveCategoriesWithoutFilters(){
        List<String> results;
        Integer countResults;

        Test.startTest();
        results = ReportFinderFilterController.getCategories();
        Test.stopTest();

        countResults = results.size();

        System.assertEquals(0, countResults, 'Expect 0 records to be returned');
    }


    /*******************************************************************************************************
    * @description Tests retrieving active records that are not assigned to any report
    */
    @isTest
    private static void testRetrieveJobsWithoutFilters(){
        List<String> results;
        Integer countResults;

        Test.startTest();
        results = ReportFinderFilterController.getJobFunctions();
        Test.stopTest();

        countResults = results.size();

        System.assertEquals(0, countResults, 'Expect 0 records to be returned');
    }



    /*******************************************************************************************************
    * @description Tests retrieving picklist values
    */
    @isTest
    private static void testRetrieveTypes(){
        List<String> results;
        Integer countResults;
        List<String> reportTypes = new List<String>();
        Integer countActiveValues;

        Schema.DescribeFieldResult reportTypeFields = Report_Finder_Item__c.Type__c.getDescribe();
        for(Schema.PicklistEntry fld : reportTypeFields.getPicklistValues()){
            if(fld.isActive() == true){
                reportTypes.add(fld.getValue());
            }   
        }

        Test.startTest();
        results = ReportFinderFilterController.getReportTypes();
        Test.stopTest();

        countResults = results.size();
        countActiveValues = reportTypes.size();

        System.assert(countActiveValues == countResults, 'Expect matching counts of active picklist values');
    }

    
}