report-finder-package-md-source/objects/Report_Finder_Item__c.object
<CustomObject>
    <description>These records hold details about reports, including filters, tags, types, and thumbnails.</description>
    <label>Report Finder Item</label>
    <nameField>
        <displayFormat>RFI-{0}</displayFormat>
        <label>Report Finder Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Finder Items</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Access_URL__c</fullName>
        <label>Access URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Item_Name__c</fullName>
        <label>Item Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Long_Description__c</fullName>
        <label>Long Description</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Publish_Status__c</fullName>
        <label>Publish Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Not Published</fullName>
                </value>
                <value>
                    <fullName>Beta</fullName>
                    <isActive>false</isActive>
                    <label>Beta</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Thumbnail_URL__c</fullName>
        <label>Thumbnail URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce Dashboard</fullName>
                </value>
                <value>
                    <fullName>Salesforce Report</fullName>
                </value>
                <value>
                    <fullName>Salesforce View</fullName>
                </value>
                <value>
                    <fullName>Tableau Dashboard</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

report-finder-package-md-source/objects/Report_Finder_User_Bookmark__c.object
<CustomObject>
    <description>Associative entity between Report Finder Items and Users. Used to bookmark/favorite reports for user quick reference.</description>
    <label>Report Finder User Bookmark</label>
    <nameField>
        <displayFormat>RFUBM-{0}</displayFormat>
        <label>Report Bookmark #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Finder User Bookmarks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Bookmarked_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bookmarked By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Bookmarked_By</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Report_Finder_Item__c</fullName>
        <label>Report Finder Item</label>
        <referenceTo>Report_Finder_Item__c</referenceTo>
        <relationshipLabel>Report Finder User Bookmarks</relationshipLabel>
        <relationshipName>Report_Finder_User_Bookmarks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/classes/ReportBookmarkController_TEST.cls
/**
* @author Ben Repak u0884669
* @date 2022-September
*
* @description Test class for ReportBookmarkController
*/
@isTest
public with sharing class ReportBookmarkController_TEST {


    @TestSetup
    static void makeData(){
        Report_Finder_Item__c rfi = new Report_Finder_Item__c();
        rfi.Item_Name__c = 'Test Report Finder Item';
        rfi.Short_Description__c = 'Short Description';
        rfi.Long_Description__c = 'Long Description';
        rfi.Publish_Status__c = 'Published';
        rfi.Type__c = 'Tableau Dashboard';
        rfi.Access_URL__c = 'https://utah.edu';
        rfi.Thumbnail_URL__c = '/bogus_url/';
        insert rfi;
    }

    /*******************************************************************************************************
    * @description Tests creating a new bookmark for a specific report finder item. Assumes the user has not bookmarked the report before.
    */
    @isTest   
    private static void testAddNewBookmark(){
        Integer beforeCount;
        Integer afterCount;
        // get report from setup method
        Report_Finder_Item__c rfi = [SELECT Id FROM Report_Finder_Item__c WHERE Item_Name__c = 'Test Report Finder Item'];

        // get bookmarks for current report before running tests
        List<Report_Finder_User_Bookmark__c> beforeBookmarks = [SELECT Id FROM Report_Finder_User_Bookmark__c WHERE Report_Finder_Item__c = :rfi.id];
        List<Report_Finder_User_Bookmark__c> afterBookmarks;

        Test.startTest();
        // test adding a bookmark
        ReportBookmarkController.updateBookmark(rfi.id, true);
        Test.stopTest();

        // get bookmarks for current report after running tests
        afterBookmarks = [SELECT Id FROM Report_Finder_User_Bookmark__c WHERE  Report_Finder_Item__c = :rfi.id];

        // check before/after counts 
        beforeCount = beforeBookmarks.size();
        afterCount = afterBookmarks.size();

        System.assertEquals(0, beforeCount, 'Expect no bookmarks before running test');
        System.assertEquals(1, afterCount, 'Expect 1 bookmark after running test');
    }


    /*******************************************************************************************************
    * @description Tests ignoring a request to create a new bookmark for a specific report finder item. Assumes the user has not bookmarked the report before.
    */
    @isTest   
    private static void testAddExistingBookmark(){
        Integer beforeCount;
        Integer afterCount;
        // get report from setup method
        Report_Finder_Item__c rfi = [SELECT Id FROM Report_Finder_Item__c WHERE Item_Name__c = 'Test Report Finder Item'];

        // create a bookmark for the report
        Id currentUser = UserInfo.getUserId();
        Report_Finder_User_Bookmark__c bm = new Report_Finder_User_Bookmark__c();
        bm.Bookmarked_By__c = currentUser;
        bm.Report_Finder_Item__c = rfi.id;
        insert bm;

        // get bookmarks for current report before running tests
        List<Report_Finder_User_Bookmark__c> beforeBookmarks = [SELECT Id FROM Report_Finder_User_Bookmark__c WHERE Report_Finder_Item__c = :rfi.id];
        List<Report_Finder_User_Bookmark__c> afterBookmarks;

        Test.startTest();
        // test adding a bookmark
        ReportBookmarkController.updateBookmark(rfi.id, true);
        Test.stopTest();
        // get bookmarks for current report after running tests
        afterBookmarks = [SELECT Id FROM Report_Finder_User_Bookmark__c WHERE  Report_Finder_Item__c = :rfi.id];

        // check before/after counts 
        beforeCount = beforeBookmarks.size();
        afterCount = afterBookmarks.size();

        System.assertEquals(1, beforeCount, 'Expect 1 bookmark before running test');
        System.assertEquals(1, afterCount, 'Expect 1 bookmark after running test');
    }


  /*******************************************************************************************************
    * @description Tests removing a bookmark for a specific report finder item. Assumes the user has bookmarked the report before.
    */
    @isTest   
    private static void testRemoveBookmark(){
        Integer beforeCount;
        Integer afterCount;

        // get report from setup method
        Report_Finder_Item__c rfi = [SELECT Id FROM Report_Finder_Item__c WHERE Item_Name__c = 'Test Report Finder Item'];

        // create a bookmark for the report
        Id currentUser = UserInfo.getUserId();
        Report_Finder_User_Bookmark__c bm = new Report_Finder_User_Bookmark__c();
        bm.Bookmarked_By__c = currentUser;
        bm.Report_Finder_Item__c = rfi.id;
        insert bm;
               
        // get bookmarks for current report before running tests
        List<Report_Finder_User_Bookmark__c> beforeBookmarks = [SELECT Id FROM Report_Finder_User_Bookmark__c WHERE Report_Finder_Item__c = :rfi.id];
        List<Report_Finder_User_Bookmark__c> afterBookmarks;

        Test.startTest();
        // test removing a bookmark
        ReportBookmarkController.updateBookmark(rfi.id, false);
        Test.stopTest();

        // get bookmarks for current report after running tests
        afterBookmarks = [SELECT Id FROM Report_Finder_User_Bookmark__c WHERE  Report_Finder_Item__c = :rfi.id];

        // check before/after counts 
        beforeCount = beforeBookmarks.size();
        afterCount = afterBookmarks.size();

        System.assertEquals(1, beforeCount, 'Expect 1 bookmark before running test');
        System.assertEquals(0, afterCount, 'Expect 0 bookmarks after running test');
        
    }
}