report-finder-package-md-source/objects/Report_Finder_Category__c.object
<CustomObject>
    <description>Tags that can be applied to organize and filter Report Finder Items</description>
    <label>Report Finder Category</label>
    <nameField>
        <displayFormat>RFC-{0}</displayFormat>
        <label>Report Finder Category #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Finder Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Category_Name__c</fullName>
        <label>Category Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

report-finder-package-md-source/objects/Report_Finder_Category_Filter__c.object
<CustomObject>
    <description>Junction object linking Report Finder Item and Report Finder Category</description>
    <label>Report Finder Category Filter</label>
    <nameField>
        <displayFormat>RFCF-{0}</displayFormat>
        <label>Report Finder Category Filter #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Finder Category Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Report_Finder_Category__c</fullName>
        <label>Report Finder Category</label>
        <referenceTo>Report_Finder_Category__c</referenceTo>
        <relationshipName>Report_Finder_Category_Filters</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Report_Finder_Item__c</fullName>
        <label>Report Finder Item</label>
        <referenceTo>Report_Finder_Item__c</referenceTo>
        <relationshipLabel>Report Finder Category Filters</relationshipLabel>
        <relationshipName>Report_Finder_Category_Filters</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

report-finder-package-md-source/objects/Report_Finder_Item__c.object
<CustomObject>
    <description>These records hold details about reports, including filters, tags, types, and thumbnails.</description>
    <label>Report Finder Item</label>
    <nameField>
        <displayFormat>RFI-{0}</displayFormat>
        <label>Report Finder Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Finder Items</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Access_URL__c</fullName>
        <label>Access URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Item_Name__c</fullName>
        <label>Item Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Long_Description__c</fullName>
        <label>Long Description</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Publish_Status__c</fullName>
        <label>Publish Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Not Published</fullName>
                </value>
                <value>
                    <fullName>Beta</fullName>
                    <isActive>false</isActive>
                    <label>Beta</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Thumbnail_URL__c</fullName>
        <label>Thumbnail URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce Dashboard</fullName>
                </value>
                <value>
                    <fullName>Salesforce Report</fullName>
                </value>
                <value>
                    <fullName>Salesforce View</fullName>
                </value>
                <value>
                    <fullName>Tableau Dashboard</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

report-finder-package-md-source/objects/Report_Finder_Job_Function__c.object
<CustomObject>
    <description>Tags that can be applied to organize and filter Report Finder Items. Relevant to job functions within the organization.</description>
    <label>Report Finder Job Function</label>
    <nameField>
        <displayFormat>RFJF-{0}</displayFormat>
        <label>Job Function #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Finder Job Functions</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Job_Function_Name__c</fullName>
        <label>Job Function Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

report-finder-package-md-source/objects/Report_Finder_Job_Function_Filter__c.object
<CustomObject>
    <description>Junction object between Report Finder Item and Report Finder Job Function</description>
    <label>Report Finder Job Function Filter</label>
    <nameField>
        <displayFormat>RFJBF-{0}</displayFormat>
        <label>Job Function Filter #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Finder Job Function Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Job_Function__c</fullName>
        <label>Job Function</label>
        <referenceTo>Report_Finder_Job_Function__c</referenceTo>
        <relationshipLabel>Report Finder Job Function Filters</relationshipLabel>
        <relationshipName>Report_Finder_Job_Function_Filter</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Report_Finder_Item__c</fullName>
        <label>Report Finder Item</label>
        <referenceTo>Report_Finder_Item__c</referenceTo>
        <relationshipLabel>Report Finder Job Function Filters</relationshipLabel>
        <relationshipName>Report_Finder_Job_Function_Filter</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

report-finder-package-md-source/objects/Report_Finder_User_Bookmark__c.object
<CustomObject>
    <description>Associative entity between Report Finder Items and Users. Used to bookmark/favorite reports for user quick reference.</description>
    <label>Report Finder User Bookmark</label>
    <nameField>
        <displayFormat>RFUBM-{0}</displayFormat>
        <label>Report Bookmark #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Finder User Bookmarks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Bookmarked_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bookmarked By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Bookmarked_By</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Report_Finder_Item__c</fullName>
        <label>Report Finder Item</label>
        <referenceTo>Report_Finder_Item__c</referenceTo>
        <relationshipLabel>Report Finder User Bookmarks</relationshipLabel>
        <relationshipName>Report_Finder_User_Bookmarks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/classes/ReportFinderController.cls
public with sharing class ReportFinderController {
    
    static Integer PAGE_SIZE = 6;

    public class ReportInfo {
        @AuraEnabled
        public String id { get; set; }
        @AuraEnabled
        public String name { get; set; }
        @AuraEnabled
        public String thumbnail { get; set; }
        @AuraEnabled
        public String longDescription { get; set; }
        @AuraEnabled
        public String shortDescription { get; set; }
        @AuraEnabled
        public String type { get; set; }
        @AuraEnabled
        public Boolean isBookmarked { get; set; }
        @AuraEnabled
        public String accessUrl { get; set; }
        @AuraEnabled
        public String[] jobFunctions { get; set; }
        @AuraEnabled
        public String[] categories { get; set; }
        @AuraEnabled
        public Boolean isNew { get; set; }
        @AuraEnabled
        public Boolean isRecentlyModified { get; set; }

        public ReportInfo(){

        }

        public ReportInfo(Report_Finder_Item__c item){
            this.id = item.Id;
            this.name = item.Item_Name__c;
            this.thumbnail = item.Thumbnail_URL__c;
            this.longDescription = item.Long_Description__c;
            this.shortDescription = item.Short_Description__c + ' Click to learn more.';
            this.type = item.Type__c;
            this.isBookmarked = (item.Report_Finder_User_Bookmarks__r.size() > 0)? true : false;
            this.accessUrl = item.Access_URL__c;
            this.jobFunctions = new List<String>{'Job1','Job2'};
            this.categories = new List<String>{'This is a word','Cat2','Another word','Cat4','Cat5'};
        }

    }

    @AuraEnabled
    public static PagedResult refreshReports(ReportFinderFilter filters, Integer pageNumber) {
        return getReports(filters, pageNumber);
    }


    @AuraEnabled(cacheable=true)
    public static PagedResult getReports(ReportFinderFilter filters, Integer pageNumber) {
        //https://github.com/trailheadapps/ebikes-lwc/blob/main/force-app/main/default/classes/ProductController.cls

        List<ReportInfo> reports = new List<ReportInfo>();
        String key, whereClause = '';
        String[] jobFunctions, type,categories, criteria = new List<String>{};
        Id currentUser = UserInfo.getUserId();
        if (filters != null) {
            if (!String.isEmpty(filters.searchKey)) {
                String cleansedKey = String.escapeSingleQuotes(filters.searchKey);
                key = '%' + filters.searchKey + '%';
                criteria.add('(Item_Name__c LIKE : key OR Short_Description__c LIKE : key)');
            }
            
            // job function filters
            if (filters.jobFunctions != null && filters.jobFunctions.size() > 0) {
                jobFunctions = filters.jobFunctions;
                criteria.add('Id IN (SELECT Report_Finder_Item__c FROM Report_Finder_Job_Function_Filter__c WHERE Job_Function__r.Job_Function_Name__c IN :jobFunctions)');
            }

            // type filters
            if (filters.type != null && filters.type.size() > 0) {
                type = filters.type;
                criteria.add('Type__c = :type');
            }

            // category / purpose filters
            if (filters.categories != null && filters.categories.size() > 0) {
                categories = filters.categories;
                system.debug('categories --> ' + categories);
                criteria.add('Id IN (SELECT Report_Finder_Item__c FROM Report_Finder_Category_Filter__c WHERE Report_Finder_Category__r.Category_Name__c IN :categories)');
            }


            // bookmarks only
            if(filters.bookmarksOnly == true){
                criteria.add('Id IN (SELECT Report_Finder_Item__c FROM Report_Finder_User_Bookmark__c WHERE Bookmarked_By__c = :currentUser)');
            }

           
         
        }
            criteria.add('Publish_Status__c != \'Not Published\' AND Publish_Status__c != \'\'');

            if (criteria.size() > 0) {
                whereClause = 'WHERE ' + String.join(criteria, ' AND ');
                system.debug('criteria --> ' + criteria);
                system.debug('where clause --> ' + whereClause);
            }
        

        Integer pageSize = ReportFinderController.PAGE_SIZE;
        Integer offset = (pageNumber - 1) * pageSize;
        PagedResult result = new PagedResult();
        result.pageSize = pageSize;
        

        
        string queryString =    'SELECT Id, Item_Name__c,Thumbnail_URL__c, Name, Long_Description__c,Short_Description__c, Type__c, Publish_Status__c, Access_URL__c ' + 
            ',(SELECT Id, Name FROM Report_Finder_User_Bookmarks__r WHERE Bookmarked_By__c = : currentUser) ' + 
            ' FROM Report_Finder_Item__c ' +
            
            whereClause + 
            ' WITH SECURITY_ENFORCED' +
            ' ORDER BY Item_Name__c LIMIT :pageSize OFFSET :offset';

            result.totalItemCount = Database.countQuery('SELECT count() FROM Report_Finder_Item__c ' + whereClause);

            result.pageNumber = ( result.totalItemCount <= result.pageSize ? 1 : pageNumber);


        
        

        for(Report_Finder_Item__c item : Database.query(queryString)){
            ReportInfo report = new ReportInfo(item);
            reports.add(report);

        }

        result.records = reports;
        system.debug('result --> ' + result);
        system.debug('result.totalItemCount --> ' + result.totalItemCount);


        return result;




    }







}