report-finder-package-md-source/objects/Report_Finder_Item__c.object
<CustomObject>
    <description>These records hold details about reports, including filters, tags, types, and thumbnails.</description>
    <label>Report Finder Item</label>
    <nameField>
        <displayFormat>RFI-{0}</displayFormat>
        <label>Report Finder Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Finder Items</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

report-finder-package-md-source/objects/Report_Finder_Item_Usage__c.object
<CustomObject>
    <label>Report Finder Item Usage</label>
    <nameField>
        <displayFormat>RFIU-{0}</displayFormat>
        <label>Report Finder Item Usage #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Finder Item Usages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Accessed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Accessed By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Report_Finder_Item_Usages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Accessed_Date__c</fullName>
        <label>Accessed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Report_Finder_Item__c</fullName>
        <label>Report Finder Item</label>
        <referenceTo>Report_Finder_Item__c</referenceTo>
        <relationshipLabel>Report Finder Item Usages</relationshipLabel>
        <relationshipName>Report_Finder_Item_Usages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/classes/ReportFinderUsageController.cls
/**
* @author Ben Repak
* @date 2022-September
*
* @description Controller used in the Report Finder App to insert / delete Report_Finder_Item_Usage__c records
*/


public without sharing class ReportFinderUsageController {

    // current date / time for use with timestamping usage log
    @TestVisible
    private static DateTime todayDateTime = System.now();

    /*******************************************************************************************************
    * @description Inserts/Updates use log records for specific Report Finder Items that are opened from the Report Finder App
    * @param reportId Id of Report_Finder_Item__c to be bookmarked or unbookmarked
    */
    @AuraEnabled(cacheable=false)
    public static void logItemUsage(Id reportId){
        // build usage log record for current user
        Id currentUser = UserInfo.getUserId();
        Report_Finder_Item_Usage__c itemUsage = new Report_Finder_Item_Usage__c();
        itemUsage.Accessed_By__c = currentUser;
        itemUsage.Report_Finder_Item__c = reportId;
        itemUsage.Accessed_Date__c = todayDateTime;

        // try to insert the usage log
        try{
            insert itemUsage;
        }catch(Exception e){
            system.debug('error inserting usage log record --> ' + e);
            throw new AuraHandledException('An error occured --> ' + e);
        }
    }
}