force-app/main/default/objects/Advancement_Report__c/Advancement_Report__c.object-meta.xml
<CustomObject>
    <label>Advancement Report</label>
    <nameField>
        <displayFormat>AR-{0}</displayFormat>
        <label>Advancement Report #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advancement Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Advancement_Report__c/fields/Publish_Status__c.field-meta.xml
<CustomField>
    <fullName>Publish_Status__c</fullName>
    <label>Publish Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Not Published</fullName>
            </value>
            <value>
                <fullName>Beta</fullName>
                <isActive>false</isActive>
                <label>Beta</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

report-finder-package-md-source/objects/Report_Finder_Category__c.object
<CustomObject>
    <description>Tags that can be applied to organize and filter Report Finder Items</description>
    <label>Report Finder Category</label>
    <nameField>
        <displayFormat>RFC-{0}</displayFormat>
        <label>Report Finder Category #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Finder Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Category_Name__c</fullName>
        <label>Category Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

report-finder-package-md-source/objects/Report_Finder_Category_Filter__c.object
<CustomObject>
    <description>Junction object linking Report Finder Item and Report Finder Category</description>
    <label>Report Finder Category Filter</label>
    <nameField>
        <displayFormat>RFCF-{0}</displayFormat>
        <label>Report Finder Category Filter #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Finder Category Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Report_Finder_Category__c</fullName>
        <label>Report Finder Category</label>
        <referenceTo>Report_Finder_Category__c</referenceTo>
        <relationshipName>Report_Finder_Category_Filters</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Report_Finder_Item__c</fullName>
        <label>Report Finder Item</label>
        <referenceTo>Report_Finder_Item__c</referenceTo>
        <relationshipLabel>Report Finder Category Filters</relationshipLabel>
        <relationshipName>Report_Finder_Category_Filters</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

report-finder-package-md-source/objects/Report_Finder_Item__c.object
<CustomObject>
    <description>These records hold details about reports, including filters, tags, types, and thumbnails.</description>
    <label>Report Finder Item</label>
    <nameField>
        <displayFormat>RFI-{0}</displayFormat>
        <label>Report Finder Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Finder Items</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Publish_Status__c</fullName>
        <label>Publish Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Not Published</fullName>
                </value>
                <value>
                    <fullName>Beta</fullName>
                    <isActive>false</isActive>
                    <label>Beta</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce Dashboard</fullName>
                </value>
                <value>
                    <fullName>Salesforce Report</fullName>
                </value>
                <value>
                    <fullName>Salesforce View</fullName>
                </value>
                <value>
                    <fullName>Tableau Dashboard</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

report-finder-package-md-source/objects/Report_Finder_Job_Function__c.object
<CustomObject>
    <description>Tags that can be applied to organize and filter Report Finder Items. Relevant to job functions within the organization.</description>
    <label>Report Finder Job Function</label>
    <nameField>
        <displayFormat>RFJF-{0}</displayFormat>
        <label>Job Function #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Finder Job Functions</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Job_Function_Name__c</fullName>
        <label>Job Function Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

report-finder-package-md-source/objects/Report_Finder_Job_Function_Filter__c.object
<CustomObject>
    <description>Junction object between Report Finder Item and Report Finder Job Function</description>
    <label>Report Finder Job Function Filter</label>
    <nameField>
        <displayFormat>RFJBF-{0}</displayFormat>
        <label>Job Function Filter #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Finder Job Function Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Job_Function__c</fullName>
        <label>Job Function</label>
        <referenceTo>Report_Finder_Job_Function__c</referenceTo>
        <relationshipLabel>Report Finder Job Function Filters</relationshipLabel>
        <relationshipName>Report_Finder_Job_Function_Filter</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Report_Finder_Item__c</fullName>
        <label>Report Finder Item</label>
        <referenceTo>Report_Finder_Item__c</referenceTo>
        <relationshipLabel>Report Finder Job Function Filters</relationshipLabel>
        <relationshipName>Report_Finder_Job_Function_Filter</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/classes/ReportFinderFilterController.cls
/**
* @author Ben Repak u0884669
* @date 2022-September
*
* @description Controller used in the Report Finder App to retreive data for the filters lwc
*/

public with sharing class ReportFinderFilterController {
   
    /*******************************************************************************************************
    * @description Retreives Report_Finder_Job_Function__c records to build a list of filter items 
    * @return a list of active job function names from the Report_Finder_Job_Function__c object that have a published report associated
    */
    @AuraEnabled(cacheable=true)
    public static List<String> getJobFunctions() {
        List<String> jobFunctions = new List<String>();
        // for(Report_Finder_Job_Function__c jobFunction : [SELECT Job_Function_Name__c FROM Report_Finder_Job_Function__c WHERE Is_Active__c = TRUE ORDER BY Job_Function_Name__c ASC]){
        for(Report_Finder_Job_Function__c jobFunction : [SELECT Job_Function_Name__c FROM Report_Finder_Job_Function__c WHERE Is_Active__c = TRUE AND Id IN (SELECT Job_Function__c FROM Report_Finder_Job_Function_Filter__c WHERE Report_Finder_Item__R.Publish_Status__c = 'Published') ORDER BY Job_Function_Name__c ASC]){
            jobFunctions.add(jobFunction.Job_Function_Name__c);
        }
        return jobFunctions;
    }

    /*******************************************************************************************************
    * @description Retreives Report_Finder_Category__c records to build a list of filter items 
    * @return a list of active category names from the Report_Finder_Category__c object that have a published report associated
    */
    @AuraEnabled(cacheable=true)
    public static List<String> getCategories() {
        List<String> categories = new List<String>();
        // for(Report_Finder_Category__c category : [SELECT Category_Name__c FROM Report_Finder_Category__c WHERE Is_Active__c = TRUE ORDER BY Category_Name__c ASC]){
        for(Report_Finder_Category__c category : [SELECT Category_Name__c FROM Report_Finder_Category__c WHERE Is_Active__c = TRUE AND Id IN (SELECT Report_Finder_Category__c FROM Report_Finder_Category_Filter__c WHERE Report_Finder_Item__R.Publish_Status__c = 'Published') ORDER BY Category_Name__c ASC]){
            categories.add(category.Category_Name__c);
        }
        return categories;
    }

    /*******************************************************************************************************
    * @description Retreives active picklist values from the Report_Finder_Item__c.Type__c field to build a list of filter items 
    * @return a list of active Report_Finder_Item__c.Type__c values from the Report_Finder_Item__c object
    */
    @AuraEnabled(cacheable=true)
    public static List<String> getReportTypes() {
        List<String> reportTypes = new List<String>();
        Schema.DescribeFieldResult reportTypeFields = Report_Finder_Item__c.Type__c.getDescribe();
            for(Schema.PicklistEntry fld : reportTypeFields.getPicklistValues()){
                if(fld.isActive() == true){
                    reportTypes.add(fld.getValue());
                }   
            }


        /* if desired to only show values for active reports, implement the following. the tradeoff is slower load time
        // try to only retrieve Type__c values associated with published reports to limit the filter values
        try{
            system.debug('try');
            AggregateResult[] groupedResults = [SELECT Type__c FROM Report_Finder_Item__c WHERE Publish_Status__c = 'Published' GROUP BY type__c ORDER BY Type__c ];
            for (AggregateResult ar : groupedResults)  {
                reportTypes.add((string)ar.get('Type__c'));
            }
        // handle any errors, and then just result to getting active picklist values and displaying them
        } Catch(exception e){
            System.debug('catch error --> ' + e);
            Schema.DescribeFieldResult reportTypeFields = Report_Finder_Item__c.Type__c.getDescribe();
            for(Schema.PicklistEntry fld : reportTypeFields.getPicklistValues()){
                if(fld.isActive() == true){
                    reportTypes.add(fld.getValue());
                }   
            }
        // if there are no records found just set the return to null, which should hide the filter component entirely
        } finally{
            system.debug('finally');
            if(reportTypes.size() == 0) {
                reportTypes = null;
            }
        }
        */
        
        return reportTypes;

    }


}