force-app/main/default/objects/Advancement_Report__c/Advancement_Report__c.object-meta.xml
<CustomObject>
    <label>Advancement Report</label>
    <nameField>
        <displayFormat>AR-{0}</displayFormat>
        <label>Advancement Report #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advancement Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

report-finder-package-md-source/objects/Report_Finder_User_Bookmark__c.object
<CustomObject>
    <description>Associative entity between Report Finder Items and Users. Used to bookmark/favorite reports for user quick reference.</description>
    <label>Report Finder User Bookmark</label>
    <nameField>
        <displayFormat>RFUBM-{0}</displayFormat>
        <label>Report Bookmark #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Finder User Bookmarks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Bookmarked_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bookmarked By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Bookmarked_By</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Report_Finder_User_Bookmark__c/fields/Advancement_Report__c.field-meta.xml
<CustomField>
    <fullName>Advancement_Report__c</fullName>
    <label>Advancement Report</label>
    <referenceTo>Advancement_Report__c</referenceTo>
    <relationshipLabel>Report Finder User Bookmarks</relationshipLabel>
    <relationshipName>Report_Finder_User_Bookmarks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ReportBookmarkController.cls
public without sharing class ReportBookmarkController {



    @AuraEnabled(cacheable=false)
    public static void updateBookmark(Id reportId, Boolean isAdd){
        Id currentUser = UserInfo.getUserId();

        Report_Finder_User_Bookmark__c bookmark = new Report_Finder_User_Bookmark__c();
        bookmark.Bookmarked_By__c = currentUser;
        bookmark.Advancement_Report__c = reportId;
        List<Report_Finder_User_Bookmark__c> bookmarks = new List<Report_Finder_User_Bookmark__c>();
        bookmarks = [SELECT Id FROM Report_Finder_User_Bookmark__c WHERE Bookmarked_By__c = :currentUser AND Advancement_Report__c = :reportId];

        if(isAdd){
           
            
            try{
                if(bookmarks.size() == 0){
                    bookmarks.add(bookmark);
                    insert bookmarks;
                } else {
                    system.debug('no insert needed');
                }

                }catch(Exception e){
                    system.debug('error --> ' + e);
                    throw new AuraHandledException('An error occured --> ' + e);

            }
            // delete
        } else {
            if(bookmarks.size() > 0){
                delete bookmarks;
            }
        }

        
    }


}